global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 50.0
  publish_frequency: 50.0
  inflation_radius: 0.3
  static_map: true

  plugins:
    - {name: static_layer, type: "costmap_2d::StaticLayer"}   
    - {name: laser_obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: depth_obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
