local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  transform_rolerance: 2.4
  update_frequency: 50.0
  publish_frequency: 50.0
  static_map: false
  rolling_window: true
  width: 3
  height: 3
  resolution: 0.05
  inflation_radius: 0.2

  plugins:
    - {name: static_layer, type: "costmap_2d::StaticLayer"}      
    - {name: laser_obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: depth_obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
