<?xml version="1.0" ?>

<robot name="eSAUl" xmlns:xacro="http://www.ros.org/wiki/xacro">
  
  <xacro:property name="chassis_mass" value="5" />
  <xacro:property name="chassis_length" value="0.45" />
  <xacro:property name="chassis_width" value="0.22" />
  <xacro:property name="chassis_height" value="0.13" />

  <xacro:property name="track_mass" value="1" />
  <xacro:property name="track_rad" value="0.04" />
  <xacro:property name="track_length" value="0.04" />

  <xacro:property name="box_length" value="0.4" />
  <xacro:property name="box_width" value="0.04" />
  <xacro:property name="box_height" value="0.08" />

  <xacro:property name="wheel_friction" value="1.75" />

  <!-- INERTIAL MACROS -->
  <xacro:macro name="null_inertial">
    <inertial>
      <mass value="0.001"/>
      <inertia ixx="0.001" ixy="0" ixz="0"
               iyy="0.001" iyz="0"
               izz="0.001"/>
      </inertial>
  </xacro:macro>

  <xacro:macro name="solid_cuboid_inertial"
               params="width length height mass *origin">
    <inertial>
      <xacro:insert_block name="origin"/>
      <mass value="${mass}"/>
      <inertia ixx="${mass * (width * width + height * height) / 12}"
               ixy="0" ixz="0"
               iyy="${mass * (length * length + height * height) / 12}"
               iyz="0"
               izz="${mass * (width * width + length * length) / 12}"/>
    </inertial>
  </xacro:macro>

  <xacro:macro name="solid_cylinder_inertial"
               params="r h mass *origin">
    <inertial>
      <xacro:insert_block name="origin"/>
      <mass value="${mass}"/>
      <inertia ixx="${mass / 12 * (3 * r * r + h * h)}" ixy="0.0" ixz="0.0"
               iyy="${mass / 12 * (3 * r * r + h * h)}" iyz="0.0"
               izz="${mass / 2 * r * r}" />
    </inertial>
  </xacro:macro>
  <!-- INERTIAL MACROS END -->

  <link name="link_chassis">
    <collision>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
    </collision>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 ${track_rad}"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <xacro:solid_cuboid_inertial
          length="${chassis_length}" width="${chassis_width}"
          height="${chassis_height}" mass="${chassis_mass}">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:solid_cuboid_inertial>
  </link>

  <xacro:macro name="link_track" params="name">
    <link name="${name}">
      <collision name="${name}_track_col_box">
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <geometry>
          <box size="${box_length} ${box_width} ${box_height}"/>
        </geometry>
      </collision>
      <visual name="${name}_track_vis_box">
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <geometry>
          <box size="${box_length} ${box_width} ${box_height}"/>
        </geometry>
      </visual>
      <collision name="${name}_track_col_back_wheel">
        <origin rpy="0 1.5708 1.5708" xyz="${-box_length/2} 0 0"/>
        <geometry>
          <cylinder length="${track_length}" radius="${track_rad}"/>
        </geometry>
      </collision>
      <visual name="${name}_track_vis_back_wheel">
        <origin rpy="0 1.5708 1.5708" xyz="${-box_length/2} 0 0"/>
        <geometry>
          <cylinder length="${track_length}" radius="${track_rad}"/>
        </geometry>
      </visual>
      <collision name="${name}_track_col_front_wheel">
        <origin rpy="0 1.5708 1.5708" xyz="${box_length/2} 0 0"/>
        <geometry>
          <cylinder length="${track_length}" radius="${track_rad}"/>
        </geometry>
      </collision>
      <visual name="${name}_track_vis_front_wheel">
        <origin rpy="0 1.5708 1.5708" xyz="${box_length/2} 0 0"/>
        <geometry>
          <cylinder length="${track_length}" radius="${track_rad}"/>
        </geometry>
      </visual>
      <xacro:solid_cuboid_inertial
            length="${chassis_length}" width="${chassis_width}"
            height="${chassis_height}" mass="${chassis_mass}">
        <origin xyz="0 0 0" rpy="0 0 0" />
      </xacro:solid_cuboid_inertial>
    </link>
    <gazebo reference="${name}">
      <mu1>${wheel_friction}</mu1>
      <mu2>${wheel_friction}</mu2>
      <material>Gazebo/Black</material>
      <kp>10000000</kp>
      <kd>1</kd>
    </gazebo>
  </xacro:macro>

  <xacro:macro name="joint_wheel" params="name child origin_xyz">
    <joint name="${name}" type="fixed">
      <origin rpy="0 0 0" xyz="${origin_xyz}"/>
      <child link="${child}"/>
      <parent link="link_chassis"/>
      <!-- <axis rpy="0 0 0" xyz="0 1 0"/> -->
      <!-- <joint_properties damping="1.0" friction="1.0"/> -->
    </joint>
    <gazebo reference="${name}">
      <!-- This one is used to disable convertion of fixed joints into links -->
      <preserveFixedJoint>true</preserveFixedJoint>
    </gazebo>
  </xacro:macro>

	<xacro:link_track name="track_left" />
	<xacro:joint_wheel name="joint_left" child="track_left" origin_xyz="0 ${-chassis_width/2-box_width/2} ${-track_rad}" />
  
	<xacro:link_track name="track_right" />
	<xacro:joint_wheel name="joint_right" child="track_right" origin_xyz="0 ${chassis_width/2+box_width/2} ${-track_rad}" />

	<gazebo>
    <plugin filename="libESAUL_plugin.so" name="simple_tracked_vehicle">
    <!-- <plugin filename="libSimpleTrackedVehiclePlugin.so" name="simple_tracked_vehicle"> -->
        <body>link_chassis</body>
        <left_track>track_left</left_track>
        <right_track>track_right</right_track>
        <track_mu>2</track_mu>
        <track_mu2>0.5</track_mu2>
    </plugin>
    <!-- <plugin filename="libKeysToCmdVelPlugin.so" name="keyboard_control"> -->
        <!-- <publish_as_twist>true</publish_as_twist> -->
        <!-- <cmd_vel_topic>~/simple_tracked/cmd_vel_twist</cmd_vel_topic> -->
    <!-- </plugin> -->
	</gazebo>

 </robot>
